---
title: "Q5-regression"
date: "5/4/2022"
output: pdf_document
---

```{r}
hurrican <- read_csv("./hurrican703.csv") %>% 
  janitor::clean_names() %>% 
  separate(time, into = c("date", "hour"), sep = " ") %>% 
  filter(hour == "00:00:00)" | hour == "06:00:00)" | hour == "12:00:00)" | hour == "18:00:00)") %>% 
  mutate(hour = str_replace(hour, ":00:00\\)", ""),
         hour = as.numeric(hour),
         date = str_replace(date, "\\(", ""),
         date = yday(date)) %>% 
  group_by(id) %>% 
  mutate(baseline_month = first(month),
         latitude_d = lead(latitude) - latitude,
         longitude_d = lead(longitude) - longitude,
         wind_kt_d = wind_kt - lag(wind_kt),
         wind_kt_2 = lead(wind_kt)) %>% 
  na.omit() %>%
  rename(year = season) %>% 
  ungroup() %>% 
  mutate(season = case_when(baseline_month %in% c("December","January","February") ~ "Winter",
                   baseline_month %in% c("March","April","May") ~ "Spring",
                   baseline_month %in% c("June","July","August") ~ "Summer",
                   baseline_month %in% c("September","October","November") ~ "Fall"),
         nature = as.factor(nature)) %>% 
  relocate(14,9,11,12,13,15,2,4) %>% 
  ### Drop the hurricane data point( < 5) 
  filter(!(id %in% c("TEN:UNNAMED.1988","EIGHT.2013", "TEN.2007", "JOSE.2005", "AMELIA.1978",
                     "BRET.2005", "FERNAND.2013", "FIFTEEN:UNNAMED.1988", "KYLE.1996")))

name_1 = unique(hurrican$id)
res_1 <- read_csv("res_1_3rd_edition.csv") %>% 
  mutate(id = name_1) %>% 
  dplyr::select(c(2:7,18))
colnames(res_1) = c("rmse", "beta_0", "beta_1", "beta_2", "beta_3", "beta_4", "id")
  
combine_res = left_join(res_1, hurrican, by = "id") %>% 
  group_by(id) %>% 
  do(head(., n = 1))
```

```{r}
## beta1
l1 = lm(beta_1 ~ season + year + nature, data = combine_res)
summary(l1)

plot(combine_res$year, combine_res$beta_2)
## beta2
l2 = lm(beta_2 ~ season + year + nature, data = combine_res)
summary(l2)

## beta3
l3 = lm(beta_3 ~ season + year + nature, data = combine_res)
summary(l3)

## beta4 
l4 = lm(beta_4 ~ season + year + nature, data = combine_res)
summary(l4)
```

