---
title: "P8160 Group Project 3: Bayesian Modeling of Hurricane Trajectories"
author: "Anyu Zhu | Haotian Wu | Wenhan Bao | Yiming Li | Qihang Wu"
date: "5/6/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background and Objective

Hurricanes are large rotating tropical storms with winds in excess of 119 kilometers per hour (74 mph). They usually form between June 1 and November 30 in the Atlantic Ocean but can develop in other oceans as well. They are known as typhoons in the western Pacific and cyclones in the Indian Ocean[1].

When a hurricane approaches land, tremendous damage can occur to the nearby cities. Therefore, scientists continue to improve their ability to forecast hurricanes. The sooner they can access accurate information about a hurricane’s location and intensity, the better the chances to minimize the hurricane’s impacts. 

In this project, we firstly built a Bayesian model based on the track data of 703 hurricanes in the North Atlantic area since 1950. A Markov Chain Monte Carlo (MCMC) algorithm was designed to generate the distribution of parameters. With the start time and type of each hurricane, the estimated coefficients from the Bayesian model were used to explore the seasonal differences and wind speed changes over years. Finally, we also explored the characteristics of hurricanes associated with the damage and deaths.


# Data Descriptions and Preprocessing

The first dataset hurrican703.csv collected the track data of 703 hurricanes in the North Atlantic area since 1950. For all the hurricanes, their locations (longitude \& latitude) and maximum wind speed were recorded every 6 hours. The variables include ID, Season, starting Month, Nature, time, Latitude, Longitude, Wind.kt. We created three new variables: changes of latitude and longitude, as well as the wind speed between the time t and $(t-6)$. For splitting the train and test set, we removed the hurricanes with observations less than 5. We built a regression model predicting wind speed based on this dataset. 

The second dataset hurricanoutcome2.csv recorded the damages and death caused by 46 hurricanes in the U.S, and some features extracted from the hurricane records. To explore the characteristics related with death and damage, we combined the coefficients results from the first model with the second dataset by hurricane ID. 


# Statistical Methods
## Posterior Distribution and Conditional Distributions 
### Likelihood

For each hurricane $i$ and $k_{i}$'s time points, we have the following Bayesian model: $$Y_{i}(t+6)=\beta_{0i}+\beta_{1i} Y_{i}(t)+\beta_{2i} \Delta_{i1}(t)+\beta_{3i} \Delta_{i2}(t)+\beta_{4 i} \Delta_{i 3}(t)+\varepsilon_{i}(t),$$ where $Y_{i}(t)$ is the wind speed at time $t$, $\Delta_{i1}$, $\Delta_{i2}$, and $\Delta_{i3}$ are the changes of latitude, longitude, and the wind speed between time point $t$ and $t - 6$, respectively. $\varepsilon_{i}(t)$ follows a normal distributions with mean zero and variance $\sigma^2$. The above Bayesian model can be simplified as: $$Y_{i}(t+6) = x_{i}(t) + \varepsilon_{i}(t),$$ where $\beta_{i} = (\beta_{0i}, \beta_{1i}, ...,\beta_{4i}) \sim N\left(0, \sigma^2\right).$ Based on the property of the multivariate linear regression model, for each hurricane $i$, we have: $$Y_{i}\mid X_{i} \sim N_{k_{i}}\left(x_{i} \beta_{i}, \sigma^{2} I_{k_{i}}\right),$$ where $I_{k_{i}}$ is an identity matrix with $k_{i}$ dimensions.

Thus, we can consider the following distribution of each hurricane $i$: $$f\left(y_{i} \mid \beta_{i}, \sigma^{2}\right)=\left[(2 \pi)^{k_{i}} \cdot \operatorname{det}\left(\sigma^{2} I_{k_{i}}\right)\right]^{-\frac{1}{2}} \cdot \exp \left\{-\frac{1}{2}\left(y_{i}-x_{i} \beta_{i}\right)^{\top} \left(\sigma^{2} I_{k_{i}}\right)^{-1}\left(y_{i}-x_{i} \beta_{i}\right)\right\}$$.

From above, we derive the following likelihood function:
$$
\begin{aligned}
f\left(y \mid B, \sigma^{2}\right)&=\prod_{i=1}^{n} f\left(y_{i} \mid \beta_{i}, \sigma^{2}\right) \\
&=\prod_{i=1}^{n}\left(\left[(2 \pi)^{k_{i}} \cdot \operatorname{det}\left(\sigma^{2} I_{k i}\right)\right]^{-\frac{1}{2}} \cdot \exp \left\{-\frac{1}{2}\left(y_{i}-x_{i} \beta_{i}\right)^{\top} \left(\sigma^{2} I_{k_{i}}\right)^{-1}\left(y_{i}-x_{i} \beta_{i}\right)\right\}\right)\end{aligned}
$$

### Prior distributions

We assume the following non-informative prior distributions:
$$\beta_{i}=\left(\beta_{0 i}, \beta_{1 i}, \ldots, \beta_{4 i}\right) \sim N_{5}(\mu, \Sigma),$$ where $B=\left(\beta_{1}^{\top}, \beta_{2}^{\top}, \ldots, \beta_{n}^{\top}\right)^{\top}$ and $n$ is the number of hurricanes. So,
$$\pi(B | \mu, \Sigma^{-1})=\prod_{i=1}^{n} f\left(\beta_{i}\right) \propto \operatorname{det}(\Sigma)^{-n / 2} \cdot \exp \left\{-\frac{1}{2} \sum_{i}\left[\left(\beta_{i}-\mu\right)^{\top} (\Sigma)^{-1} \left(\beta_{i}-\mu\right)\right]\right\}.$$ Also, $\pi\left(\sigma^{2}\right) \propto \frac{1}{\sigma^{2}}; \hspace{.2cm} \pi(\mu) \propto 1; \hspace{.2cm} \pi\left(\Sigma^{-1}\right) \propto|\Sigma|^{-(d+1)} \cdot \exp \left(-\frac{1}{2} \Sigma^{-1}\right).$

### Conditional posteriors

The posterior distribution is the product of the likelihood and the prior: 

$$g\left(B, \sigma^{2}, \mu, \Sigma^{-1} \mid y\right) \propto f\left(y \mid B, \sigma^{2}\right) \cdot \pi(B \mid \mu, \Sigma^{-1}) \cdot \pi\left(\sigma^{2}\right) \cdot \pi(\mu) \cdot \pi\left(\Sigma^{-1}\right),$$ so we have:

$$
\begin{aligned}
\pi\left(\sigma^{2} \mid \cdot\right) & \propto \prod_{i=1}^{n} \operatorname{det}\left(\sigma^{2} I_{k_{i}}\right)^{-\frac{1}{2}} \cdot \exp \left\{-\frac{1}{2} \Sigma_{i}\left[\left(y_{i}-x_{i} \beta_{i}\right)^{\top}\left(\sigma^{2} I_{k i}\right)^{-1}\left(y_{i}-x_{i} \beta_{i}\right)\right]\right\} \cdot \sigma^{-2} \\
&=\left(\sigma^{2}\right)^{-\frac{1}{2} \Sigma_{i} k_{i}} \cdot \exp \left\{-\frac{1}{2 \sigma^{2}} \Sigma_{i}\left[\left(y_{i}-x_{i} \beta_{i}\right)^{\top} \left(y_{i}-x_{i} \beta_{i}\right)\right]\right\} \cdot \sigma^{-2} \\
&=\left(\sigma^{2}\right)^{-1-\frac{1}{2} \Sigma_{i} k_{i}} \cdot \exp \left\{-\frac{1}{2 \sigma^{2}} \Sigma_{i} \Sigma_{t i}\left(y_{i, t}-x_{i, t} \beta_{i}\right)^{2}\right\}
\end{aligned}
$$
Therefore, $\sigma^2 \sim \text{Inverse Gamma}\left(\frac{1}{2} \Sigma_{i} k_{i}, \frac{1}{2} \Sigma_{i} \Sigma_{t_{i}}\left(y_{i, t}-x_{i, t} \beta_{i}\right)^{2}\right)$.

$$
\begin{aligned} 
\pi(\Sigma^{-1} \mid \cdot) & \propto \operatorname{det}(\Sigma)^{-n / 2} \cdot \exp \left\{-\frac{1}{2} \Sigma_{i}\left(\beta_{i}-\mu\right)^{\top} \Sigma^{-1}\left(\beta_{i}-\mu\right)\right\} \cdot \operatorname{det}(\Sigma)^{-(d+1)} \cdot \exp \left\{-\frac{1}{2} \Sigma^{-1}\right\} \\ &=\operatorname{det}(\Sigma)^{-(n/2+d+1)} \cdot \exp \left\{-\frac{1}{2}\left[\Sigma^{-1}+\Sigma_{i}\left(\beta_{i}-\mu\right)^{\top} \Sigma^{-1}\left(\beta_{i}-\mu\right)\right]\right\} \\ 
& \propto \operatorname{det}(\Sigma^{-1})^{(n+2 d+2) / 2} \cdot \exp \left\{-\frac{1}{2} \operatorname{tr}\left[\Sigma^{-1}\cdot\left(I+\Sigma_{i}\left(\beta_{i}-\mu\right)\left(\beta_{i}-\mu\right)^{\top}\right]\right\}\right.\\ 
& \propto \operatorname{det}(\Sigma^{-1})^{(n+3d+3-d-1) / 2} \cdot \exp \left\{-\frac{1}{2} \operatorname{tr}\left[\Sigma^{-1} \cdot\left(I+\Sigma_{i}\left(\beta_{i}-\mu\right)\left(\beta_{i}-\mu\right)^{\top}\right]\right\}\right.
\end{aligned}
$$
Thus $\Sigma^{-1} \sim \text {Wishart}\left(n + 3d+3,[I+\Sigma_{i}\left(\beta_{i}-\mu\right)\left(\beta_{i}-\mu\right)^{\top}\right]^{-1})$, that is: $$\Sigma \sim \text {Inverse Wishart}\left(n + 3d+3,I+\Sigma_{i}\left(\beta_{i}-\mu\right)\left(\beta_{i}-\mu\right)^{\top}\right)$$


$$
\begin{aligned}
\pi(\mu \mid \cdot) & \propto \exp \left\{-\frac{1}{2} \Sigma_{i}\left[\left(\beta_{i}-\mu\right)^{\top} \Sigma^{-1}\left(\beta_{i}-\mu\right)\right]\right\} \\
&=\exp \left\{-\frac{1}{2} \Sigma_{i}\left(\beta_{i}^{\top} \Sigma^{-1} \beta_{i}+\mu^{\top} \Sigma^{-1} \mu-2 \beta_{i}^{\top} \Sigma^{-1} \mu\right)\right\} \\
&=\exp \left\{-\frac{1}{2}\left(\Sigma_{i} \beta_{i}^{\top} \Sigma^{-1} \beta_{i}+\mu^{\top} n \Sigma^{-1} \mu-2 \Sigma_{i} \beta_{i}^{\top} \Sigma^{-1} \mu\right)\right\} \\
&=\exp \left\{-\frac{1}{2}\left(\mu^{\top} n \Sigma^{-1} \mu-2 \Sigma_{i} \beta_{i}^{\top} \Sigma^{-1} \mu+\Sigma_{i}\beta_{i}^{\top} \Sigma^{-1} \beta_{i}\right)\right\} \\
&=\exp \left\{-\frac{1}{2}(\mu^{\top} \underbrace{n\Sigma^{-1}}_{M}  \mu-2 \mu^{\top} \underbrace{\Sigma_{i} \Sigma^{-1} \beta_{i}}_{N}+\Sigma_{i} \beta_{i}^{\top} \Sigma^{-1} \beta_{i})\right\} \\
&=\exp \left\{-\frac{1}{2}\left[\left(\mu-M^{-1} N\right)^{\top} M\left(\mu-M^{-1} N\right)\right]\right\}.
\end{aligned}
$$
Therefore, $\mu \sim MVN\left(M^{-1} N, {M}^{-1}\right)$.

$$
\begin{aligned}
&\pi(B \mid \cdot) \propto \exp \left\{-\frac{1}{2} \Sigma_{i}\left[\left(y_{i}-x_{i} \beta_{i}\right)^{\top}\left(\sigma^{2} I_{k i}\right)^{-1}\left(y_{i}-x_{i} \beta_{i}\right)\right]\right\} \cdot \exp \left\{-\frac{1}{2} \Sigma_{i}\left[\left(\beta_{i}-\mu\right)^{\top} (\Sigma)^{-1} \left(\beta_{i}-\mu\right)\right]\right\} \\
&=\exp \left\{-\frac{1}{2} \Sigma_{i}\left[\left(y_{i}-x_{i} \beta_{i}\right)^{\top}\left(\sigma^{2} I_{k i}\right)^{-1}\left(y_{i}-x_{i} \beta_{i}\right)+\left(\beta_{i}-\mu\right)^{\top} \Sigma^{-1}\left(\beta_{i}-\mu\right)\right]\right\} \\
&=\exp \left\{ -\frac{1}{2} \Sigma_{i}[ y_{i}^{\top} \sigma^{-2} I_{k i} y_{i}+\beta_{i}^{\top} x_{i}^{\top} \sigma^{-2} I_{k_{i}} x_{i} \beta_{i}-2 y_{i}^{\top} \sigma^{-2} I_{k i} x_{i} \beta_{i}+\beta_{i}^{\top} \Sigma^{-1} \beta_{i}+\mu^{\top} \Sigma^{-1} \mu-2 \mu^{\top} \Sigma^{-1} \beta_{i}] \right\} \\
&=\exp \left\{-\frac{1}{2} \Sigma_{i}[y_{i}^{\top} \sigma^{-2} I_{k i} y_{i}+\mu^{\top} {\Sigma}^{-1} \mu+\beta_{i}^{\top}\left({\Sigma}^{-1}+x_{i}^{\top} {\sigma}^{-2} I_{k i} x_{i}\right) \beta_{i}-2\left(y_{i}^{\top} \sigma^{-2} I_{k i} x_{i}+\mu^{\top} \Sigma^{-1}\right) \beta_{i}] \right\}
\end{aligned}
$$


We can define the following terms:
$$R=y_{i}^{\top} \sigma^{-2} I_{k_{i}} y_{i}+\mu^{\top} \Sigma^{-1} \mu$$
$$V=\Sigma^{-1}+x_{i}^{\top} \sigma^{-2} I_{k i} x_{i}$$
$$M=\sigma^{-2} x_{i}^{\top} y_{i}+\Sigma^{-1} \mu$$

Thus, 
$\pi (B \mid \cdot) \propto \left(\beta_{i} -V^{-1} M\right)^{\top} V\left(\beta_{i}-V^{-1} M\right) \sim MVN\left(V^{-1} M, {V}^{-1}\right)$


## Gibbs Sampling
Since directly generating the above jointly density is rather complicated, we can implement the gibbs sampler to sample each variable in turn. Based on the previous conditional distributions, we updated the four parameters including $B$, $\sigma^2$, $\sum$, and $\mu$ in sequence. Finally, we selected 10,000 iterations. Note that we ignored the first 8,000 iterations to ensure the stationary distribution of the Markov chain was reached.

## Lasso and Poisson Regression Model


# Results
## Gibbs Sampling

## Task 5

## Task 6


# Discussion and Limitations


# Contributions


# Reference


# Appendix
For codes please click [$\textcolor{blue}{here}$](https://github.com/hw2849/p8160_group_project_3.git)